/**
 * site-config.ts
 * Auto-generated by compile_bio.py. Do not edit manually.
 */

export const BIO_CONFIG = {
  profile: {
    name: "Chahaven",
    initials: "C",
    avatarUrl: "/avatar.png",
    tagline: "Tea & Tranquility",
    location: "Canada",
    company: "Chahaven",
    companyUrl: "https://chahaven.ca",
  },
  social: [
  {
    "name": "Instagram",
    "url": "https://instagram.com/chahaven",
    "icon": "instagram"
  },
  {
    "name": "LinkedIn",
    "url": "https://linkedin.com/company/chahaven",
    "icon": "linkedin"
  },
  {
    "name": "GitHub",
    "url": "https://github.com/tianchengc/chahaven",
    "icon": "github"
  },
  {
    "name": "Email",
    "url": "mailto:info@chahaven.ca",
    "icon": "mail"
  }
],
  links: [
  {
    "title": "\ud83c\udf75 Book a Private Tasting Ceremony",
    "url": "https://chahaven.ca/book"
  },
  {
    "title": "\ud83d\udce6 Browse Our Curated Oolong Selection",
    "url": "https://chahaven.ca/shop"
  },
  {
    "title": "\u2709\ufe0f Join our Mindful Tea Newsletter",
    "url": "https://chahaven.ca/newsletter"
  }
],
  projects: [
  {
    "title": "Ancient Sage Green Oolong",
    "description": "Handpicked oolong leaves harvested from 100-year-old tea trees.",
    "url": "https://chahaven.ca/products/sage-green-oolong",
    "imageUrl": "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=300&q=80",
    "badge": "$24.00"
  },
  {
    "title": "Zen Ceramic Infuser Set",
    "description": "Handmade organic clay tea cup with a bamboo steeping infuser.",
    "url": "https://chahaven.ca/products/zen-infuser-set",
    "imageUrl": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=300&q=80",
    "badge": "$48.00"
  },
  {
    "title": "The Art of Slowing Down",
    "description": "How the ancient ritual of tea brewing teaches us the power of mindfulness.",
    "url": "https://chahaven.ca/blog/slowing-down",
    "imageUrl": "https://images.unsplash.com/photo-1563822249548-9a72b6353cd1?auto=format&fit=crop&w=300&q=80",
    "badge": "Blog"
  }
],
  theme: {
    primary: "#4a7c59",
    accent: "#2d4a35",
    background: "#fafaf8",
    text: "#1c1c1c",
    font: "Cormorant Garamond",
    fontSans: "Inter",
  },
} as const;

export type BioConfig = typeof BIO_CONFIG;
