/**
 * site-config.ts
 * Auto-generated by compile_home.py. Do not edit manually.
 */

export const STARTUP_CONFIG = {
  seo: {
    title: "Chahaven | Tea & Tranquility",
    description: "Tea & Tranquility",
  },
  hero: {
    badge: "✨ Premium Experience",
    heading: "Find Focus and Calm through Tea & Tranquility",
    subheading: "Escape the complexity. Tea & Tranquility tailored for your daily needs.",
    primaryCta: { text: "Book Now", href: "https://chahaven.ca" },
    secondaryCta: { text: "Learn More", href: "https://chahaven.ca" },
  },
  socialProof: {
    companies: [
      "Chahaven Rituals",
      "Direct Supply Chain",
      "Stress Decompression",
    ],
  },
  bentoFeatures: [
  {
    "title": "Private 1-on-1 or small group",
    "description": "Private 1-on-1 or small group (friends/family) traditional tea ceremony bookings.",
    "icon": "coffee",
    "className": "col-span-3 lg:col-span-2"
  },
  {
    "title": "Corporate on-site de-stress workshops",
    "description": "Corporate on-site de-stress workshops (bringing tea artists, premium leaves, and tools to offices).",
    "icon": "users",
    "className": "col-span-3 lg:col-span-1"
  },
  {
    "title": "Premium e-commerce retail line selling d",
    "description": "Premium e-commerce retail line selling direct-from-farm leaves and starter utensils.",
    "icon": "leaf",
    "className": "col-span-3 lg:col-span-1"
  }
],
  pricing: [
  {
    "plan": "Eventbrite ticket sales",
    "price": "$45",
    "period": "per seat for public tea ceremony events",
    "features": [
      "Full service access",
      "Premium direct-sourced materials",
      "Flexible scheduling",
      "Satisfaction guarantee"
    ],
    "cta": "Get Started",
    "href": "https://chahaven.ca/book",
    "highlighted": false
  },
  {
    "plan": "E-commerce retail sales",
    "price": "$25",
    "period": "session",
    "features": [
      "Full service access",
      "Premium direct-sourced materials",
      "Flexible scheduling",
      "Satisfaction guarantee"
    ],
    "cta": "Get Started",
    "href": "https://chahaven.ca/book",
    "highlighted": true
  },
  {
    "plan": "Custom corporate workshop bookings",
    "price": "$600",
    "period": "per session",
    "features": [
      "Full service access",
      "Premium direct-sourced materials",
      "Flexible scheduling",
      "Satisfaction guarantee"
    ],
    "cta": "Get Started",
    "href": "https://chahaven.ca/book",
    "highlighted": false
  }
],
  theme: {
    primary: "#4a7c59",
    accent: "#2d4a35",
    background: "#fafaf8",
    font: "Cormorant Garamond",
    fontSans: "Inter",
  },
} as const;

export type StartupConfig = typeof STARTUP_CONFIG;
